maintainer        "Jiva Technology Limited"
maintainer_email  "theo@jivatechnology.com"
license           "Apache 2.0"
description       "Provides a define to set up ssh authorized keys"
version           "0.1"
