maintainer        "Jiva Technology Limited"
maintainer_email  "theo@jivatechnology.com"
license           "Apache 2.0"
description       "Installs Vlad gem and provides a define to set up deployment for an application"
version           "0.1"
