maintainer       "Jiva Technology Limited"
maintainer_email "theo@jivatechnology.com"
license          "Apache 2.0"
description      "Provides basic wrapper for deploy resource"
version          "0.1"
