maintainer       "Jiva Technology Limited"
maintainer_email "theo@jivatechnology.com"
license          "Apache 2.0"
description      "Provides definitions for helping provision AWS services"
version          "0.1"